version: 2.1.{build}
branches:
  only:
  - master
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - '**/*.txt'
    - '**/*.png'
    - '**/*.jpg'
    - '**/*.svg'
    - '**/*.json'
    - '**/*.config'
    - '**/*.csproj'
    - '**/*.csproj.user'
    - 'Tests/'
image: Visual Studio 2019
configuration: Release
clone_depth: 5
environment:
  DEV-DATABASE-SQLSEVER-DOMAIN:
    secure: gDFNTcGbJURYooTneY4HWA==
  DEV-DATABASE-SQLSEVER-USER: orm
  DEV-DATABASE-SQLSEVER-PASSWORD:
    secure: EBwfqG8uz9iVmvOZfc7+wQ==
  DEV-DATABASE-SQLSERVER-DATABASE: yep_sky_orm
  DEV-DATABASE-MYSQL-DOMAIN:
    secure: OMbUydo/+vdnkmdHRkBNag==
  DEV-DATABASE-MYSQL-DATABASE: yep_sky_orm
  DEV-DATABASE-MYSQL-USER: root
  DEV-DATABASE-MYSQL-PASSWORD:
    secure: EBwfqG8uz9iVmvOZfc7+wQ==
services:
- mssql2012sp1
- mysql
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
before_package:
- ps: .\build.ps1
artifacts:
- path: .\.nupkgs\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: vKIav3cl0tbJXgnrn/xu8OwYTnfr3qreiJ/SAS4rwOvOi+oE6CglMuLAhobElmV0
  skip_symbols: false
  on:
    branch: master
notifications:
- provider: Email
  to:
  - m.hyl@foxmail.com
  subject: codearts
  on_build_success: true
  on_build_failure: true